// <auto-generated />
namespace ResumeBank.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class candidatesubcategoryforeignkeyadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(candidatesubcategoryforeignkeyadded));
        
        string IMigrationMetadata.Id
        {
            get { return "201812060651202_candidate-sub-category foreign key added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
