// <auto-generated />
namespace ResumeBank.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class removeattachmentcandidate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeattachmentcandidate));
        
        string IMigrationMetadata.Id
        {
            get { return "201812050953354_remove attachment candidate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
